const ErrorCodes = {
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 99,
  INVALID_FILE_TYPE_ERROR_CODE: 100,
  CSV_PARSE_ERROR_CODE: 101,
  RECORD_NOT_FOUND: 102,
};

export default ErrorCodes;
